---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./istiod-1.12.6.tgz
      sourceRef:
        kind: GitRepository
        name: repo
  interval: 10m0s
  targetNamespace: istio-system
  values:
   revision: canary

