apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: istio-system
spec:
  releaseName: istiod
  chart:
    spec:
      chart: istiod-canary
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    revision: canary
