---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: deploymentrepo
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/psbrar99/helm-upgrade

